
name: Deploy to On-premise Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Build and Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t full-app-backend:latest ./backend

      - name: Stop and remove existing container
        run: |
          docker stop backend-container || true
          docker rm backend-container || true

      - name: Run new container
        run: docker run -d -p 8000:8000 --env-file ./backend/.env --name backend-container --restart always full-app-backend:latest

      - name: Clean up old images
        run: docker image prune -a -f
